name: Static analysis

on: [push, pull_request]

concurrency:
<<<<<<< HEAD
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
=======
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
>>>>>>> b456b246614305b4d1535f6e32b105d589542824
  cancel-in-progress: true

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: '.'
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        python3 -m pip install flake8
    - name: Run linter
      run: |
        python3 -m flake8 .
